services:
    ronte_ltd_elastic.index_listener:
        class: RonteLtd\ElasticBundle\EventListener\IndexListener
        public: false
        autowire: true;
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }

    ronte_ltd_elastic.elastic_service:
        class: RonteLtd\ElasticBundle\Service\ElasticService
        arguments: ["%ronte_ltd_elastic%"]
        public: true
        autowire: true